export default {
  CREATE_POST: 'CREATE_POST', 
  SUCESSO_CREATE_POST: 'SUCESSO_CREATE_POST', 
  READ: 'READ', 
  SUCESSO_READ: 'SUCESSO_READ', 
  DELETE: 'DELETE', 
  SUCESSO_DELETE: 'SUCESSO_DELETE', 
  ALTERACAO_POSTS: 'ALTERACAO_POSTS'
}